version: '2'

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./src:/www
    links:
      - php
      - mariadb
  php:
    container_name: php
    image: sadykh/php:latest
    volumes:
      - ./src:/www
      - ./db:/var/lib/mysql
    links:
      - mariadb
  mariadb:
      container_name: db
      image: mysql:5.6.40
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=admin
       - MYSQL_DATABASE=testingDB
       - MYSQL_PASSWORD=deathcutegirl
      volumes:
       - ./mysqldata:/var/lib/mysql